### ISSUE TITLE
作者你好，请问模型训练那一部分的代码要在哪里下载呀？

### ISSUE THREAD

**Issue by lh5533223** [percent4/llm_open_triplet_extraction#3]

**Comment by percent4** [comment]
模型训练使用的框架是Firefly，可以在Github上找到，具体的模型训练配置文件可以在本项目中查找。

**Comment by lh5533223** [comment]
好的，谢谢您。还有一个问题就是那个model_eval.py文件中的from component.utils的component文件在哪里下载呀？

**Comment by lh5533223** [comment]
> 模型训练使用的框架是Firefly，可以在Github上找到，具体的模型训练配置文件可以在本项目中查找。

是Firefly框架中的component文件夹吗？请问本项目所用的firefly-baichuan-7b-spo-merge预训练权重我没有搜到，可以采用
![0E8969E9DE90038B1A6C390273785DD1](https://github.com/percent4/llm_open_triplet_extraction/assets/84327800/b98219df-77f9-4476-ab48-08c88772fd2e)
这个来替代吗？

**Comment by percent4** [comment]
在github上搜索firefly项目，而不是huggingface上。另外，firefly项目可能代码有更新过，你可以试试现在的代码是否还能用。

**Comment by lh5533223** [comment]
> 在github上搜索firefly项目，而不是huggingface上。另外，firefly项目可能代码有更新过，你可以试试现在的代码是否还能用。

作者你好，我single_chat_server_spo.py复原的网页在线测试结果如下图：
![929695BE673275F9EA38E02B20170C00](https://github.com/percent4/llm_open_triplet_extraction/assets/84327800/f7764190-c80b-4393-8830-8d1c75633e27)
有很大的问题，我觉着原因是这个地方
![929695BE673275F9EA38E02B20170C00](https://github.com/percent4/llm_open_triplet_extraction/assets/84327800/9c754b00-6f04-40f4-8224-b017a0f330c9)
源代码中s所需的预训练权重文件为firefly-baichuan-7b-spo-merge，与我下载的firefly-baichuan-7b权重文件不符。
另外，我从Github上下载的Firefly，里面的script目录中并没有所需要的checkpoint文件夹！
![929695BE673275F9EA38E02B20170C00](https://github.com/percent4/llm_open_triplet_extraction/assets/84327800/bc57904a-f023-4e39-95dc-110a7434cf9b)
求解一下！

**Comment by lh5533223** [comment]
> 在github上搜索firefly项目，而不是huggingface上。另外，firefly项目可能代码有更新过，你可以试试现在的代码是否还能用。

请问可以分享一下github上firefly项目的下载链接吗？谢谢

**Comment by lh5533223** [comment]
> 在github上搜索firefly项目，而不是huggingface上。另外，firefly项目可能代码有更新过，你可以试试现在的代码是否还能用。

我是从下面这个链接下载的Firefly
https://github.com/yangjianxin1/Firefly?tab=readme-ov-file

**Comment by percent4** [comment]
firefly-baichuan-7b-spo-merge 这个模型是你需要自己在GPU上训练的，我这边只提供了数据和训练方法。模型还是需要你自己训练的，而不是直接拿baichuan-7b模型就行了的。

**Comment by lh5533223** [comment]
> firefly-baichuan-7b-spo-merge 这个模型是你需要自己在GPU上训练的，我这边只提供了数据和训练方法。模型还是需要你自己训练的，而不是直接拿baichuan-7b模型就行了的。

好的，谢谢。请问训练方法就是按照Firefly中提及的从全量参数微调一步步来吗？
![image](https://github.com/percent4/llm_open_triplet_extraction/assets/84327800/45242909-2467-4294-ac06-b3f02d177a85)

**Comment by lh5533223** [comment]
> firefly-baichuan-7b-spo-merge 这个模型是你需要自己在GPU上训练的，我这边只提供了数据和训练方法。模型还是需要你自己训练的，而不是直接拿baichuan-7b模型就行了的。

作者，请问方便分享一下您训练好的预训练权重。我测试一下效果吗？

**Comment by lh5533223** [comment]
> firefly-baichuan-7b-spo-merge 这个模型是你需要自己在GPU上训练的，我这边只提供了数据和训练方法。模型还是需要你自己训练的，而不是直接拿baichuan-7b模型就行了的。

你好，请问可以帮一下我吗？

**Comment by percent4** [comment]
我这儿已经没有训练好的模型了，需要你自己训练的，数据集、训练方法都在项目中给出了。

**Comment by lh5533223** [comment]
> 我这儿已经没有训练好的模型了，需要你自己训练的，数据集、训练方法都在项目中给出了。

好的，谢谢你。训练代码我调好了，不过我现在的RTX 3060显卡貌似是跑步起来，训练过程中直接强制重启了

**Comment by lh5533223** [comment]
> 我这儿已经没有训练好的模型了，需要你自己训练的，数据集、训练方法都在项目中给出了。

是不是windows系统配置不了deepspeed全量参数微调。我是直接运行的Firefly的train_lora.py训练文件

**Comment by percent4** [comment]
一般是使用GPU训练的，你可以看看训练baichuan-7b模型需要多少显存。
